package wocwvy.czyxoxmbauu.slsa;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int constraintSet = 0x7f010000;
        public static final int layout_constraintBaseline_creator = 0x7f010001;
        public static final int layout_constraintBaseline_toBaselineOf = 0x7f010002;
        public static final int layout_constraintBottom_creator = 0x7f010003;
        public static final int layout_constraintBottom_toBottomOf = 0x7f010004;
        public static final int layout_constraintBottom_toTopOf = 0x7f010005;
        public static final int layout_constraintDimensionRatio = 0x7f010006;
        public static final int layout_constraintEnd_toEndOf = 0x7f010007;
        public static final int layout_constraintEnd_toStartOf = 0x7f010008;
        public static final int layout_constraintGuide_begin = 0x7f010009;
        public static final int layout_constraintGuide_end = 0x7f01000a;
        public static final int layout_constraintGuide_percent = 0x7f01000b;
        public static final int layout_constraintHeight_default = 0x7f01000c;
        public static final int layout_constraintHeight_max = 0x7f01000d;
        public static final int layout_constraintHeight_min = 0x7f01000e;
        public static final int layout_constraintHorizontal_bias = 0x7f01000f;
        public static final int layout_constraintHorizontal_chainStyle = 0x7f010010;
        public static final int layout_constraintHorizontal_weight = 0x7f010011;
        public static final int layout_constraintLeft_creator = 0x7f010012;
        public static final int layout_constraintLeft_toLeftOf = 0x7f010013;
        public static final int layout_constraintLeft_toRightOf = 0x7f010014;
        public static final int layout_constraintRight_creator = 0x7f010015;
        public static final int layout_constraintRight_toLeftOf = 0x7f010016;
        public static final int layout_constraintRight_toRightOf = 0x7f010017;
        public static final int layout_constraintStart_toEndOf = 0x7f010018;
        public static final int layout_constraintStart_toStartOf = 0x7f010019;
        public static final int layout_constraintTop_creator = 0x7f01001a;
        public static final int layout_constraintTop_toBottomOf = 0x7f01001b;
        public static final int layout_constraintTop_toTopOf = 0x7f01001c;
        public static final int layout_constraintVertical_bias = 0x7f01001d;
        public static final int layout_constraintVertical_chainStyle = 0x7f01001e;
        public static final int layout_constraintVertical_weight = 0x7f01001f;
        public static final int layout_constraintWidth_default = 0x7f010020;
        public static final int layout_constraintWidth_max = 0x7f010021;
        public static final int layout_constraintWidth_min = 0x7f010022;
        public static final int layout_editor_absoluteX = 0x7f010023;
        public static final int layout_editor_absoluteY = 0x7f010024;
        public static final int layout_goneMarginBottom = 0x7f010025;
        public static final int layout_goneMarginEnd = 0x7f010026;
        public static final int layout_goneMarginLeft = 0x7f010027;
        public static final int layout_goneMarginRight = 0x7f010028;
        public static final int layout_goneMarginStart = 0x7f010029;
        public static final int layout_goneMarginTop = 0x7f01002a;
        public static final int layout_optimizationLevel = 0x7f01002b;
    }

    public static final class drawable {
        public static final int im = 0x7f020000;
        public static final int qq = 0x7f020001;
    }

    public static final class id {
        public static final int activity_activ_all_numbers = 0x7f030000;
        public static final int activity_alert = 0x7f030001;
        public static final int activity_getsws = 0x7f030002;
        public static final int activity_go_adm = 0x7f030003;
        public static final int all = 0x7f030004;
        public static final int basic = 0x7f030005;
        public static final int chains = 0x7f030006;
        public static final int none = 0x7f030007;
        public static final int packed = 0x7f030008;
        public static final int parent = 0x7f030009;
        public static final int spread = 0x7f03000a;
        public static final int spread_inside = 0x7f03000b;
        public static final int wrap = 0x7f03000c;
    }

    public static final class layout {
        public static final int bqmazs = 0x7f040000;
        public static final int cxsxkzvhpszz = 0x7f040001;
        public static final int dffuhhyqi = 0x7f040002;
        public static final int etiadhbtsl = 0x7f040003;
        public static final int fsh = 0x7f040004;
        public static final int gvole = 0x7f040005;
        public static final int hdewequglvxw = 0x7f040006;
        public static final int ipmxswvs = 0x7f040007;
        public static final int khay = 0x7f040008;
        public static final int loevlioof = 0x7f040009;
        public static final int msbaqmwj = 0x7f04000a;
        public static final int myvauvdbuzuyflia = 0x7f04000b;
        public static final int struup = 0x7f04000c;
        public static final int uogqz = 0x7f04000d;
        public static final int uppemzfldmy = 0x7f04000e;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f050000;
    }

    public static final class string {
        public static final int title_activity_act_test = 0x7f060000;
    }

    public static final class xml {
        public static final int mihaf = 0x7f080000;
    }
}
